on:
  pull_request:
    types: opened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]'
    steps:
      - name: Auto-merge github-actions PR
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --rebase --auto
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
