on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff #v24
        with:
          globs: |
            **/*.md
            !shared-modules/**

  build:
    needs: check
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08@sha256:9c6819dd59d5170dc5bdd9ceeb61dcb69e9429ae9f9c70b5554b34e905aaa54c
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: true
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7
        id: gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
      - name: Download x86_64 Repo Artifact
        if: matrix.arch == 'aarch64'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: repo-x86_64
          path: repo
      - name: Build Flatpak
        run: |
          flatpak-builder \
            --arch=${{ matrix.arch }} \
            --disable-rofiles-fuse \
            --force-clean \
            --gpg-sign=${{ steps.gpg.outputs.fingerprint }} \
            --repo=repo \
            build
            de.bwravencl.ControllerBuddy.yml
      - name: Upload x86_64 Repo Artifact
        if: matrix.arch == 'x86_64'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: repo-x86_64
          path: repo
          retention-days: 1
      - name: Update Repo
        if: matrix.arch == 'aarch64'
        run: |
          flatpak build-update-repo \
            --gpg-sign=${{ steps.gpg.outputs.fingerprint }} \
            --generate-static-deltas \
            --prune \
            repo
      - name: Generate CNAME
        if: matrix.arch == 'aarch64'
        run: echo flatpak.controllerbuddy.org > repo/CNAME
      - name: Upload Pages Artifact
        if: matrix.arch == 'aarch64'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: repo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
